INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resses, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(40, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 'Water', '1 Colorless', 45, 1, 3, 1),
(60, 'Metapod', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', 'Water', '2 Colorless', 54, 1, 3, 2),
(80, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '20', 'Fire', 'Water', '1 Colorless', 15, 1, 3, 3),
(50, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', 'Water', '1 Colorless', 69, 1, 3, 1),
(60, 'Kakuna', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', 'Water', '2 Colorless', 33, 1, 3, 2),
(80, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', 'Water', '2 Colorless', 17, 1, 3, 3),
(50, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', NULL, '1 Colorless', 56, 1, 7, 1),
(70, 'Raticate', 'Mouse Pokémon', 'Super Fang', '—', 'Fighting', NULL, '2 Colorless', 40, 1, 7, 2),
(60, 'Farfetch’d', 'Wild Duck Pokémon', 'Leek Slap', '30', 'Electric', NULL, '1 Colorless', 27, 1, 7, 1),
(80, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Electric', NULL, '1 Colorless', 48, 1, 7, 1),

(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Electric', NULL, '2 Colorless', 34, 2, 7, 2),
(70, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '10', 'Fighting', NULL, '1 Colorless', 56, 2, 7, 1),
(80, 'Persian', 'Classy Cat Pokémon', 'Scratch', '20', 'Fighting', NULL, '2 Colorless', 42, 2, 7, 2),
(60, 'Cubone', 'Lonely Pokémon', 'Bone Attack', '20', 'Grass', NULL, '1 Colorless', 50, 2, 6, 1),
(80, 'Marowak', 'Bone Keeper Pokémon', 'Bonemerang', '30x', 'Grass', NULL, '2 Colorless', 39, 2, 6, 2),
(70, 'Exeggcute', 'Egg Pokémon', 'Hypnosis', '—', 'Fire', NULL, '1 Colorless', 52, 2, 3, 1),
(90, 'Exeggutor', 'Coconut Pokémon', 'Big Eggsplosion', '20x', 'Fire', NULL, '3 Colorless', 35, 2, 3, 2),
(60, 'Bellsprout', 'Flower Pokémon', 'Vine Whip', '10', 'Fire', NULL, '1 Colorless', 49, 2, 3, 1),
(80, 'Weepinbell', 'Flower Pokémon', 'Poisonpowder', '20', 'Fire', NULL, '2 Colorless', 36, 2, 3, 2),
(100, 'Victreebel', 'Flycatcher Pokémon', 'Acid', '20', 'Fire', NULL, '3 Colorless', 14, 2, 3, 3),

(70, 'Grimer', 'Sludge Pokémon', 'Pound', '10', 'Psychic', NULL, '1 Colorless', 48, 3, 5, 1),
(90, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', NULL, '2 Colorless', 13, 3, 5, 2),
(60, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Electric', NULL, '1 Colorless', 50, 3, 2, 1),
(80, 'Seadra', 'Dragon Pokémon', 'Water Gun', '20+', 'Electric', NULL, '2 Colorless', 32, 3, 2, 2),
(100, 'Dragonite', 'Dragon Pokémon', 'Slam', '40x', 'Electric', NULL, '3 Colorless', 4, 3, 7, 3),
(70, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', NULL, '1 Colorless', 53, 3, 4, 1),
(80, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', NULL, '2 Colorless', 9, 3, 4, 2),
(60, 'Drowzee', 'Hypnosis Pokémon', 'Pound', '10', 'Psychic', NULL, '1 Colorless', 49, 3, 5, 1),
(80, 'Hypno', 'Hypnosis Pokémon', 'Prophecy', '—', 'Psychic', NULL, '2 Colorless', 8, 3, 5, 2),
(90, 'Dragonair', 'Dragon Pokémon', 'Slam', '30x', 'Electric', NULL, '2 Colorless', 18, 3, 7, 2);
