CREATE TABLE tbl_collections (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    collectionSetName VARCHAR(100) NOT NULL,
    release_date DATE NOT NULL,
    totalCardsInCollection SMALLINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_types (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    typeName VARCHAR(30) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_stages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    stageName VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_cards (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hp SMALLINT,
    name VARCHAR(80) NOT NULL,
    info TEXT,
    attack VARCHAR(100),
    damage VARCHAR(20),
    weak VARCHAR(30),
    resses VARCHAR(30),
    retreat VARCHAR(20),
    cardNumberInCollection SMALLINT NOT NULL,
    collection_id INT UNSIGNED NOT NULL,
    type_id INT UNSIGNED NOT NULL,
    stage_id INT UNSIGNED NOT NULL,
    CONSTRAINT fk_collection FOREIGN KEY (collection_id) REFERENCES tbl_collections (id) ON DELETE CASCADE,
    CONSTRAINT fk_type FOREIGN KEY (type_id) REFERENCES tbl_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_stage FOREIGN KEY (stage_id) REFERENCES tbl_stages (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
